vich_uploader:
    db_driver: orm

    mappings:
        documentation:
            uri_prefix: /images/products
            upload_destination: '%kernel.project_dir%/public/images/products'
        photos:
            uri_prefix: /images/photos
            upload_destination: '%kernel.project_dir%/public/images/photos'
